### ISSUE TITLE
Add description how custom binary is compiled

### ISSUE THREAD

**Issue by lenvm** [mmoskal/blackmagic-bluepill#1]
Thank you for this repository!

I am interested to understand how you compile the custom binary of the Black Magic Probe firmware, with the changes compared to default configuration using PROBE_HOST=stlink.

The link in the README.md to the patches applied (https://github.com/blacksphere/blackmagic/compare/master...mmoskal:bluepill?expand=1) doesn’t show any differences between your fork and the blackmagic/master branch.

Can you add to the README.md how the changes are introduced to the binaries and how one binary is compiled instead of the usual two binaries (blackmagic_dfu.bin and blackmagic.bin)?

**Comment by mmoskal** [comment]
I fixed the link, the build command is at the bottom of README, it's just `make PROBE_HOST=stlink BLUEPILL=1`
